octopus:
  enviroments:
    - development
    - production
  development:
    shards:
      canada:
        host: localhost
        adapter: mysql
        database: canada_shard
        password: 123455
      brazil:
        host: localhost
        adapter: mysql
        database: brazil_shard
        password: 123455
      mexico:
        host: localhost
        adapter: mysql
        database: mexico_shard
        password: 123455
